# Generated by Django 5.0.1 on 2025-11-14 14:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Cargo Name')),
                ('dimensions', models.CharField(max_length=100, verbose_name='Dimensions (W*H*D)')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('volume', models.FloatField(verbose_name='Volume (m³)')),
                ('requires_cold', models.BooleanField(default=False, verbose_name='Requires Refrigeration')),
                ('requires_box', models.BooleanField(default=False, verbose_name='Requires Box')),
                ('requires_crate', models.BooleanField(default=False, verbose_name='Requires Crate')),
                ('forklift_needed', models.BooleanField(default=False, verbose_name='Forklift Needed')),
                ('license_c_required', models.BooleanField(default=False, verbose_name='Category C License Required')),
                ('license_ce_required', models.BooleanField(default=False, verbose_name='Category C+E License Required')),
                ('license_adr_required', models.BooleanField(default=False, verbose_name='ADR Certification Required')),
                ('special_training', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Special Training Required')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargo Items',
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('distance_km', models.FloatField(verbose_name='Distance (km)')),
                ('estimated_time', models.DurationField(verbose_name='Estimated Time')),
                ('holiday_blocked', models.BooleanField(default=False, verbose_name='Holiday Blocked')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('license_c', models.BooleanField(default=False, verbose_name='Category C License')),
                ('license_ce', models.BooleanField(default=False, verbose_name='Category C+E License')),
                ('license_adr', models.BooleanField(default=False, verbose_name='ADR Certification')),
                ('forklift_certified', models.BooleanField(default=False, verbose_name='Forklift Certification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Holiday Date')),
                ('country', models.CharField(max_length=2, verbose_name='Country Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('license_c_allowed', models.IntegerField(choices=[(0, 'Restricted'), (1, 'Allowed')], default=0, verbose_name='Category C Allowed')),
                ('license_ce_allowed', models.IntegerField(choices=[(0, 'Restricted'), (1, 'Allowed')], default=0, verbose_name='Category C+E Allowed')),
                ('license_adr_allowed', models.IntegerField(choices=[(0, 'Restricted'), (1, 'Allowed')], default=0, verbose_name='ADR Allowed')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'ordering': ['date'],
                'unique_together': {('date', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20, unique=True, verbose_name='Registration Number')),
                ('type', models.CharField(choices=[('refrigerated', 'Refrigerated'), ('box', 'Box'), ('cargo', 'Cargo')], max_length=20, verbose_name='Vehicle Type')),
                ('capacity_weight', models.FloatField(verbose_name='Max Load Capacity (kg)')),
                ('capacity_volume', models.FloatField(verbose_name='Max Volume Capacity (m³)')),
                ('has_forklift', models.BooleanField(default=False, verbose_name='Has Forklift')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_transit', 'In Transit'), ('maintenance', 'Maintenance')], default='available', max_length=20, verbose_name='Status')),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle', to='api.user', verbose_name='Current Driver')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255, verbose_name='Current Location')),
                ('distance_to_dest_km', models.FloatField(verbose_name='Remaining Distance (km)')),
                ('estimated_arrival', models.DateTimeField(verbose_name='Estimated Arrival Time')),
                ('tracking_points', models.JSONField(default=dict, verbose_name='Location History')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='api.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Tracker',
                'verbose_name_plural': 'Trackers',
                'db_table': 'tracker',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='Status')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('planned_date', models.DateField(verbose_name='Planned Departure Date')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Date')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.cargo', verbose_name='Cargo')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.route', verbose_name='Route')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to='api.user', verbose_name='Assigned Driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.user', verbose_name='Client')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.vehicle', verbose_name='Assigned Vehicle')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-creation_date'],
            },
        ),
    ]
