# Generated by Django 5.0.1 on 2025-11-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='volume',
        ),
        migrations.AddField(
            model_name='cargo',
            name='height',
            field=models.FloatField(default=1, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='length',
            field=models.FloatField(default=1, verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='width',
            field=models.FloatField(default=1, verbose_name='Width (cm)'),
        ),
    ]
