# Generated by Django 5.0.1 on 2025-11-14 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_order_origin_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='current_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_vehicle', to='api.user', verbose_name='Current Driver'),
        ),
    ]
